version: 2.1

owner-repo: &owner-repo
  owner-repo: nmiyake/dockergen

orbs:
  go: palantir/go@dev:develop-f9c9f00e87d034185b3fcb451b4871223e6469b4

jobs:
  verify:
    executor:
      name: go/darwin-linux-no-cgo
      <<: *owner-repo
    steps:
      - run: go version
      - run: |
             echo "GO111MODULE: ${GO111MODULE}"

  verify-no-mod:
    executor:
      name: go/darwin-linux-no-cgo
      <<: *owner-repo
      module: false
    steps:
      - run: go version
      - run: |
          echo "GO111MODULE: ${GO111MODULE}"

workflows:
  version: 2
  verify-test:
    jobs:
      - verify
      - verify-no-mod
