owner-repo: &owner-repo
  owner-repo: nmiyake/dockergen

version: 2.1

orbs:
  go: palantir/go@0.0.15
  godel: palantir/godel@0.0.15

executor-param: &executor-param
  executor:
    name: go/darwin-linux-no-cgo
    <<: *owner-repo

workflows:
  version: 2
  verify-test:
    jobs:
      - godel/verify:
          <<: *executor-param
      - godel/test:
          executor:
            name: go/golang-docker
            <<: *owner-repo
          docker: true
