version: 2.1

orbs:
  go: palantir/go@dev:develop-5b319175ff3286271daa401bc1c1a9e419e88dc5
  godel: palantir/godel@dev:develop-a09ca259cd8d6c54d0fa7f9020b734d878cbb79e

executor-param: &executor-param
  executor:
    name: go/darwin-linux-no-cgo
    owner-repo: palantir/distgo

all-tags-filter: &all-tags-filter
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  dist-publish:
    jobs:
      - godel/verify:
          <<: *all-tags-filter
          <<: *executor-param
      - godel/test:
          <<: *all-tags-filter
          executor:
            name: go/golang-docker
            owner-repo: palantir/distgo
          docker: true
      - godel/dist:
          <<: *all-tags-filter
          <<: *executor-param
      - godel/bintray-publish:
          requires:
            - godel/verify
            - godel/test
            - godel/dist
          filters:
            tags:
              only: /^v?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?(-alpha[0-9]+)?$/
            branches:
              ignore: /.*/
          <<: *executor-param
          bintray-subject: palantir
          bintray-repo: releases
          bintray-product: distgo
