plugins:
  resolvers:
    - https://palantir.bintray.com/releases/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.0.0-rc2
environment:
  GO111MODULE: on
  GOFLAGS: -mod=vendor
exclude:
  names:
    - "\\..+"
    - "vendor"
  paths:
    - "godel"
